library:
  source-dirs: src
  exposed-modules:
  - Vein.Syntax.Lexer
  - Vein.Syntax.Parser
  - Vein.Core.Monoidal.Monoidal
tests:
  vein-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vein
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- base
- llvm-hs >= 8.0.0
- llvm-hs-pure
- prettyprinter
- text
- data-fix
- containers
- mtl
- transformers
- array
- split
- optparse-applicative
name: vein
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: arrow-world/vein
license: BSD3
executables:
  vein-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vein
description: Please see the README on GitHub at <https://github.com/githubuser/vein#readme>
build-tools:
- alex
- happy